# This file contains records describing all of the system services recognized
# by the MINTIA2 Executive. It feeds the GenSrv tool to automatically
# generate some tables.
#
# Flags:
#  'C': can wait on a continuation

# Ob
# NAME                              ARGUMENTS                 FLAGS
{ OsOpenObject                      1                                         }
{ OsClose                           1                                         }

# Ex
# NAME                              ARGUMENTS                 FLAGS
{ OsReadEvent                       1                                         }
{ OsSignalEvent                     1                                         }
{ OsResetEvent                      1                                         }
{ OsCreateEvent                     3                                         }

# Ps
# NAME                              ARGUMENTS                 FLAGS
{ OsCreateJob                       4                                         }
{ OsSignalJob                       3                                         }
{ OsRemoveProcessJob                1                                         }
{ OsAddProcessJob                   2                                         }
{ OsCreateThread                    7                                         }
{ OsExitThread                      1                                         }
{ OsSuspendThread                   1                                         }
{ OsUnsuspendThread                 2                                         }
{ OsReadStatusThread                1                                         }
{ OsQueryThread                     2                                         }
{ OsSignalThread                    2                                         }
{ OsMaskSignalThread                3                                         }
{ OsDeliverOnWaitSignalThread       3                                         }
{ OsGetFaultStatusThread            1                                         }
{ OsSleepThread                     2                         C               }
{ OsCreateProcess                   5                                         }
{ OsSignalProcess                   2                                         }
{ OsSignalActivationProcess         1                                         }
{ OsAwaitActivationProcess          3                         C               }
{ OsOpenProcessByPid                2                                         }
{ OsReadStatusProcess               1                                         }
{ OsQueryProcess                    2                                         }
{ OsQueryProcessByPid               2                                         }
{ OsSetGroupProcess                 2                                         }
{ OsSetBasePriorityProcess          2                                         }
{ OsEnablePrivilegeProcess          2                                         }
{ OsDisablePrivilegeProcess         2                                         }
{ OsGrantPrivilegeProcess           2                                         }
{ OsRevokePrivilegeProcess          2                                         }
{ OsExitProcess                     1                                         }
{ OsQueryProcessCount               0                                         }
{ OsQueryProcesses                  2                                         }
{ OsSetQuotaProcess                 2                                         }
{ OsQueryQuotaProcess               2                                         }
{ OsOpenGroupByPid                  2                                         }
{ OsSignalGroup                     2                                         }
{ OsOpenMyGroup                     1                                         }
{ OsNewSessionProcess               1                                         }
