# This file contains records describing all of the system services recognized
# by the MINTIA2 Executive. It feeds the GenSrv tool to automatically
# generate some tables.
#
# Flags:
#  'C': can wait on a continuation

# Ob
# NAME                              ARGS        ARGS64        FLAGS
{ OsOpenObject                      1           0                             }
{ OsClose                           1           0                             }

# Ex
# NAME                              ARGS        ARGS64        FLAGS
{ OsReadEvent                       1           0                             }
{ OsSignalEvent                     1           0                             }
{ OsResetEvent                      1           0                             }
{ OsCreateEvent                     3           0                             }

# Ps
# NAME                              ARGS        ARGS64        FLAGS
{ OsCreateJob                       4           0                             }
{ OsSignalJob                       3           0                             }
{ OsRemoveProcessJob                1           0                             }
{ OsAddProcessJob                   2           0                             }
{ OsCreateThread                    7           0                             }
{ OsExitThread                      1           0                             }
{ OsSuspendThread                   1           0                             }
{ OsUnsuspendThread                 2           0                             }
{ OsReadStatusThread                1           0                             }
{ OsQueryThread                     2           0                             }
{ OsSignalThread                    2           0                             }
{ OsMaskSignalThread                3           0                             }
{ OsDeliverOnWaitSignalThread       3           0                             }
{ OsGetFaultStatusThread            1           0                             }
{ OsSleepThread                     2           0             C               }
{ OsCreateProcess                   5           0                             }
{ OsSignalProcess                   2           0                             }
{ OsSignalActivationProcess         1           0                             }
{ OsAwaitActivationProcess          3           0             C               }
{ OsOpenProcessByPid                2           0                             }
{ OsReadStatusProcess               1           0                             }
{ OsQueryProcess                    2           0                             }
{ OsQueryProcessByPid               2           0                             }
{ OsSetGroupProcess                 2           0                             }
{ OsSetBasePriorityProcess          2           0                             }
{ OsEnablePrivilegeProcess          2           0                             }
{ OsDisablePrivilegeProcess         2           0                             }
{ OsGrantPrivilegeProcess           2           0                             }
{ OsRevokePrivilegeProcess          2           0                             }
{ OsExitProcess                     1           0                             }
{ OsQueryProcessCount               0           0                             }
{ OsQueryProcesses                  2           0                             }
{ OsSetQuotaProcess                 2           0                             }
{ OsQueryQuotaProcess               2           0                             }
{ OsOpenGroupByPid                  2           0                             }
{ OsSignalGroup                     2           0                             }
{ OsOpenMyGroup                     1           0                             }
{ OsNewSessionProcess               1           0                             }
